." Process this file with
." groff -man -Tascii jellyman.1
."
.TH Jellyman

.Sh NAME
.B Jellyman - a Jellyfin Manager for the Jellyfin generic linux amd64.tar.gz package

.SH VERSION
.B Jellyman - The Jellyfin Manager - v1.6.7

.SH SYNOPSIS
.B jellyman

.SH DESCRIPTION
.B Jellyman
is a set of scripts to install/manage and update the jellyfin-combined tar.gz generic linux package

.SH USAGE
.B SYNTAX
- jellyman -[COMMAND] [PARAMETER]
.TP
.SS COMMANDS
.TP
.B -b, --backup                 [DIRECTORY] Input directory to output backup archive.
.TP
.B -d, --disable                Disable Jellyfin on System Start.
.TP
.B -e, --enable                 Enable Jellyfin on System Start.
.TP
.B -h, --help                   Print this Help.
.TP
.B -i, --import                 [FILE.tar] Input file to Import jellyfin-backup.tar.
└── This will only work if on your new OS/setup you have your Media directories exactly the same as your old OS/setup.
.TP
.B -p, --permissions            [DIRECTORY - optional] Reset the permissions of Jellyfin's Media Library or supplied directory.
└── Uses 'chmod -R 770' on your media directory.
.TP
.B -r, --restart                Restart Jellyfin.
.TP
.B -s, --start                  Start Jellyfin.
.TP
.B -S, --stop                   Stop Jellyfin.
.TP
.B -t, --status                 Status of Jellyfin.
.TP
.B -u, --update-jellyfin        [URL - optional] Downloads and updates the current stable or supplied Jellyfin version.
└── NOTE - Supplied URL has to end with jellyfin_x.x.x_<ARCHITECTURE>.tar.gz
.TP
.B -U, --update-jellyman        Update Jellyman - The CLI Tool.
└── Checks and downloads most recent version from GitHub.
.TP
.B -ub, --update-beta           Update Jellyfin to the most recent Beta.
.TP
.B -v, --version                Get the current installed version of Jellyfin.
.TP
.B -vd, --version-download      Download an available Jellyfin version from the stable repository.
└── Provides a list of currently installed versions of Jellyfin for you to download.
.TP
.B -vs, --version-switch        Switch Jellyfin version for another previously installed version.
└── Provides a list of currently installed versions of Jellyfin for you to switch to.
.TP
.B -rv, --remove-version        Remove a Jellyfin version.
└── Provides a list of currently installed versions of Jellyfin for you to remove.
.TP
.B -rc, --recertify             Removes old https certifications and creates new ones for the next 365 days.
.TP
.B -rn, --rename                Batch renaming script for TV shows.
.TP
.B -ls, --library-scan          Tell Jellyfin to scan your media library.
.TP
.B -cp, --change-http           Change Jellyfins http network port - Default = 8096.
.TP
.B -cps, --change-https         Change Jellyfins https network port - Default = 8920.
.TP
.B -ik, --import-key            Import an API key.
.TP
.B -md, --media-directory       Change the Media Directory for Jellyman.
.TP
.B -tc, --transcode             Transcode a file/directory with a GB per hour filter (1.5GB is recommended)
.TP
.B -tcp, --transcode-progress   View the progress of current transcode
.TP
.B -tcs, --transcode-stop       Stop the current transcode process.
.TP
.B -X, --uninstall              Uninstall Jellyfin and Jellyman Completely.
└── Ignores the Media Directory.

.SH EXAMPLE
.TP
.B To stop Jellyfin, disable on startup, backup, and then start the Jellyfin server:
.TP
.B 'sudo jellyman -S -d -b /home/$USER/ -s'

.SH FILES
.TP
.I
/opt/jellyfin
.TP
.I
/etc/jellyfin.conf
.TP
.I
/bin/jellyman

.SH URL TO NEW VERSIONS
.PP
***WARNING*** ONLY USE COMBINED(Web & Server) PACKAGES
https://repo.jellyfin.org/releases/server/linux/versions/

.SH COPYRIGHT
.PP
Copyright 2021 Smiley McSmiles. All rights reserved
https://www.github.com/Smiley-McSmiles/jellyman

.SH CREDITS
.PP
Jellyman and this man page was created by Smiley McSmiles <SmileyMcSmiles@Proton.me>

