." Process this file with
." groff -man -Tascii jellyman.1
."
.TH Jellyman

.Sh NAME
.B Jellyman - a Jellyfin Manager for the Jellyfin generic linux amd64.tar.gz package

.SH VERSION
.B Jellyman - The Jellyfin Manager - v1.8.3

.SH SYNOPSIS
.B jellyman

.SH DESCRIPTION
.B Jellyman
is a set of scripts to install/manage and update the jellyfin-combined tar.gz generic linux package

.SH USAGE
.B SYNTAX
- jellyman -[COMMAND] [PARAMETER]
.TP
.SS COMMANDS
.TP
.B -b, --backup                 [DIRECTORY] Input directory to output backup archive.
.BR
    ├── jellyman -b "/path/to/backup/directory" will output a jellyfin-backup.tar to that directory.
.BR
    ├── jellyman -ba will perform an automatic backup. But only if automatic backups are set up.
.BR
    └── jellyman -bu will launch the automatic backup setup utility.
.TP
.B -ba, --backup-auto           Perform an automatic backup.
.TP
.B -bu, --backup-utility        Start the automatic backup utility.
.TP
.B -d, --disable                Disable Jellyfin on System Start.
.TP
.B -e, --enable                 Enable Jellyfin on System Start.
.TP
.B -h, --help                   Print this Help.
.TP
.B -i, --import                 [FILE.tar - optional] Input file to Import jellyfin-backup.tar.
.BR
    ├── Media metadata will only import if your new OS/setup and old OS/setup media folders are exactly the same.
.BR
    └── User and Web-UI configurations will still import just fine however.
.TP
.B -p, --permissions            [DIRECTORY - optional] Reset the permissions of Jellyfin's Media Library or supplied directory.
.BR
    └── Uses 'chmod -R 770' on your media directory.
.TP
.B -r, --restart                Restart Jellyfin.
.TP
.B -s, --start                  Start Jellyfin.
.TP
.B -S, --stop                   Stop Jellyfin.
.TP
.B -t, --status                 Status of Jellyfin.
.TP
.B -u, --update-jellyfin        [URL - optional] Downloads and updates the current stable or supplied Jellyfin version.
.BR
    └── NOTE - Supplied URL has to end with jellyfin_xx.x.x-<ARCHITECTURE>.tar.gz
.TP
.B -U, --update-jellyman        Update Jellyman - The CLI Tool.
.BR
    └── Checks and downloads most recent version from GitHub.
.TP
.B -ub, --update-beta           Update Jellyfin to the most recent Beta.
.TP
.B -v, --version                Get the current installed version of Jellyfin.
.TP
.B -vd, --version-download      Download an available Jellyfin version from the stable repository.
.BR
    └── Provides a list of currently installed versions of Jellyfin for you to download.
.TP
.B -vs, --version-switch        Switch Jellyfin version for another previously installed version.
.BR
    └── Provides a list of currently installed versions of Jellyfin for you to switch to.
.TP
.B -rv, --remove-version        Remove a Jellyfin version.
.BR
    └── Provides a list of currently installed versions of Jellyfin for you to remove.
.TP
.B -vl, --view-log              Choose from a list of logs to view.
.TP
.B -rc, --recertify             Removes old https certifications and creates new ones for the next 365 days.
.TP
.B -rn, --rename                Batch renaming script for TV shows.
.TP
.B -ls, --library-scan          Tell Jellyfin to scan your media library.
.TP
.B -cp, --change-http           Change Jellyfins http network port - Default = 8096.
.TP
.B -cps, --change-https         Change Jellyfins https network port - Default = 8920.
.TP
.B -ik, --import-key            Import an API key.
.TP
.B -md, --media-directory       Change the Media Directory for Jellyman.
.TP
.B -tc, --transcode             Transcode a file/directory with a GB per hour filter.
.BR
    ├── 1.5GB/hr is recommended for 1080p.
.BR
    ├── 3GB/hr is recommended for 4k.
.BR
    ├── Now uses AV1 codec (No HDR).
.BR
    └── Please be careful as this can delete media files.
.BR
        └── Select [no] to keep original files to preserve your media.
.TP
.B -tcp, --transcode-progress   View the progress of current transcode.
.TP
.B -tcs, --transcode-stop       Stop the current transcode process.
.TP
.B -X, --uninstall              Uninstall Jellyfin and Jellyman Completely.
.BR
    └── Ignores the Media Directory.

.SH EXAMPLE
.TP
.B To stop Jellyfin, disable on startup, backup, and then start the Jellyfin server:
.TP
.B 'sudo jellyman -S -d -b /home/$USER/ -s'

.SH FILES
.TP
.I
/opt/jellyfin
.TP
.I
/etc/jellyfin.conf
.TP
.I
/bin/jellyman

.SH URL TO NEW VERSIONS
.PP
List of supported official Jellyfin packages:
.PP
https://repo.jellyfin.org/files/server/linux/stable/

.SH COPYRIGHT
.PP
Copyright 2021-2024 WOOSAH (Smiley McSmiles). All rights reserved
.PP
https://www.github.com/Smiley-McSmiles/jellyman

.SH CREDITS
.PP
Jellyman and this man page was created by WOOSAH <WOOSAAH@Proton.me>

